### ISSUE TITLE
Add OpenGov Track Selector

### ISSUE THREAD

**Issue by Leemo94** [MathCryptoDoc/math-crypto-webpage#1]
GM! First of all I absolutely love your delegation hash generator, amazing work! 
Also kudos on updating it to include removing & undelegating voting power.

I have another feature request which I think could be great.
Could you add an option, whereby if a user presses it, they can then customize the tracks for which they wish to delegate?

The default would remain as all 15 tracks, but if a user for example wanted to not delegate for Root and Whitelisted Caller, they can select something like "advanced options" and then uncheck those tracks.

Again, amaaaazing work! Voted for your referendum :)

**Comment by MathCryptoDoc** [comment]
Hi Leemo! Thanks for the nice words and the good suggestion.

Modifying the tracks would indeed be more in line with the idea of OpenGov delegations. Small tipper is something that almost everybody wants to delegate, for example, but not so with Root.

Implementing this functionality is a little more difficult since votes depend on the referenda tracks. I will give it a try in the coming days...

**Comment by MathCryptoDoc** [comment]
Selection of referenda tracks in now on the [website](https://backend-opengov.math-crypto.com/). Votes that belong to the these tracks are also removed. Please give it a try. I tried a few cases myself and it seems to work. You can reopen the issue if needed.
